---

services:
  camsur:
    image: camsur:0.0.1
    container_name: camsur
    restart: on-failure
    read_only: true
    networks:
      - network1
    ports:
      - '8888:8888'
    environment:
      HOST: modbus_0
      PORT: 25002
      UNIT: 1
      TIME_PERIOD: 1000
      CONTROL_TIME_PERIOD: 500
      TIMEOUT: 500
      RETRIES: 1
    tmpfs:
      - /temp:uid=5678,gid=5678
    volumes:
      - camsur_config_vol:/app/appconfig
      - camsur_temp_vol:/app/temp
networks:
  network1:
    name: edgenet
    external: true

volumes:
  camsur_config_vol:
    name: camsur_config_vol
  camsur_temp_vol:
    name: camsur_temp_vol
...
