---
version: '3.7'

services:
  camsur:
    image: camsur:0.0.0
    container_name: camsur
    restart: on-failure
    read_only: true
    networks:
      - network1
    ports:
      - '8888:8888'
    environment:
      HOST: 192.168.1.41
      PORT: 502
      UNIT: 1
      TIME_PERIOD: 1000
      CONTROL_TIME_PERIOD: 1000
      TIMEOUT: 500
      RETRIES: 1
    tmpfs:
      - /temp:uid=5678,gid=5678
    volumes:
      - camsur_config_vol:/app/appconfig
      - motion_captured_vol:/app/motion_captured
      - manually_captured_vol:/app/manually_captured
      - temp_vol:/app/temp
networks:
  network1:
    name: edgenet
    external: true

volumes:
  camsur_config_vol:
    name: camsur_config_vol
  motion_captured_vol:
    name: motion_captured_vol
  manually_captured_vol:
    name: manually_captured_vol
  temp_vol:
    name: temp_vol
...
